apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec: 
      containers:
        - name: users
          image: hritikraj003/kub-net:latest
          env: 
            - name: AUTH_ADDRESS
              # value: "10.99.204.62"
              value: "auth-service.default"